### ISSUE TITLE
Installation script

### ISSUE THREAD

**Issue by mallanos** [craabreu/ufedmm#23]
Hi, I'm trying to install the package following these instructions that I found on read the docs
git clone https://github.com/craabreu/ufedmm.git
cd ufedmm
python setup.py install
However, there is no setup.py script on the repository. How should I install it?
Thanks

**Comment by craabreu** [comment]
You can now install the package from the [mdtools](https://anaconda.org/mdtools) conda channel. Please refer to the [documentation](https://craabreu.github.io/ufedmm) for detailed instructions.

**Comment by craabreu** [comment]
Solved.
