### ISSUE TITLE
cvpack.HelixRMSDContent CV,  RMSD computation error 

### ISSUE THREAD

**Issue by shitanshu-cell** [craabreu/ufedmm#24]
Hi , 

I am trying to use helixRMSDContent() CV in ufedmm, defined under cvpack.

It is showing a number of particles mismatch error .

Code i used is as follows : 

```
residues=list(pdb.topology.residues())
num_atoms=pdb.topology.getNumAtoms()
AH_RMSD=cvpack.HelixRMSDContent(residues[0:37],num_atoms)
system.AH_RMSD=ufedmm.CollectiveVariable('AH_RMSD',AH_RMSD)
``` 
error :
 openmm.OpenMMException: RMSDForce: Number of reference positions does not equal number of particles in the System

Kindly have a look

**Comment by craabreu** [comment]
#27 solves this issue
